# Generated by Django 3.0.8 on 2020-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Example title ABOUT ME', max_length=100, verbose_name='Заголовок блока')),
                ('slogan', models.CharField(default='Lorem slogan', max_length=200, verbose_name='Ваш слоган')),
                ('description', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', verbose_name='Подробная информация о ВАС')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография в блоке')),
            ],
            options={
                'verbose_name': 'About me',
                'verbose_name_plural': 'About me',
            },
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название клиента в базе данных')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография логотипа')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='contact_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact me', max_length=100, verbose_name='Название блока')),
                ('slogan', models.CharField(default='Example slogan', max_length=150, verbose_name='Ваш слоган')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваша электронная почта')),
                ('place', models.CharField(default='Example', max_length=100, verbose_name='Ваше месторасположение')),
                ('description', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Contact me',
                'verbose_name_plural': 'Contact me',
            },
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='©Developed by Potemkin Nikita', max_length=1000, verbose_name='Текст футора')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
            },
        ),
        migrations.CreateModel(
            name='intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.TextField(default='Example slogan', verbose_name='Слоган')),
                ('motto', models.TextField(default='Example motto', verbose_name='Девиз')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография интро')),
                ('description', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', max_length=5000, verbose_name='Информация о себе')),
            ],
            options={
                'verbose_name': 'Intro',
                'verbose_name_plural': 'Intro',
            },
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название фотографии в базе данных')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография в портфолио')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='servisec', max_length=50, verbose_name='Заголовок блока')),
                ('slogan', models.TextField(default='Example slogan', max_length=300, verbose_name='Слоган')),
                ('name_service_first', models.CharField(default='First service', max_length=50, verbose_name='Название первой услуги')),
                ('description_service_first', models.TextField(default='Description first service', max_length=300, verbose_name='Описание первой услуги')),
                ('image_service_first', models.ImageField(upload_to='', verbose_name='Картинка первой услуги')),
                ('name_service_second', models.CharField(default='First service', max_length=50, verbose_name='Название второй услуги')),
                ('description_service_second', models.TextField(default='Description first service', max_length=300, verbose_name='Описание второй услуги')),
                ('image_service_second', models.ImageField(upload_to='', verbose_name='Картинка второй услуги')),
                ('name_service_third', models.CharField(default='First service', max_length=50, verbose_name='Название третьей услуги')),
                ('description_service_third', models.TextField(default='Description first service', max_length=300, verbose_name='Описание третьей услуги')),
                ('image_service_third', models.ImageField(upload_to='', verbose_name='Картинка третьей услуги')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='side_bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Example title', max_length=100, verbose_name='Заголовок')),
                ('main', models.CharField(default='Main', max_length=20, verbose_name="Название кнопки 'Главная'")),
                ('services', models.CharField(default='Services', max_length=20, verbose_name="Название кнопки 'Услуги'")),
                ('portfolio', models.CharField(default='Portfolio', max_length=20, verbose_name="Название кнопки 'Портфолио'")),
                ('clients', models.CharField(default='Clients', max_length=20, verbose_name="Название кнопки 'Клиенты'")),
                ('about_me', models.CharField(default='About me', max_length=20, verbose_name="Название кнопки 'Обо мне'")),
                ('contacts', models.CharField(default='Contacts', max_length=20, verbose_name="Название кнопки 'Связь со мной'")),
            ],
            options={
                'verbose_name': 'Sidebar',
                'verbose_name_plural': 'Sidebar',
            },
        ),
    ]
