# Generated by Django 3.0.8 on 2020-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='title', max_length=50, verbose_name='Заголовок блока'),
        ),
    ]
