# Generated by Django 3.0.8 on 2020-08-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200730_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_me',
            options={'verbose_name': 'Информация обо мне', 'verbose_name_plural': 'Информация обо мне'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Логотип постоянных клиентов', 'verbose_name_plural': 'Логотипы постоянных клиентов'},
        ),
        migrations.AlterModelOptions(
            name='contact_me',
            options={'verbose_name': 'Контакты для связи', 'verbose_name_plural': 'Контакты для связи'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Подвал', 'verbose_name_plural': 'Подвал'},
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name': 'Начальный блок', 'verbose_name_plural': 'Начальный блок'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Фотография в портфолио', 'verbose_name_plural': 'Фотографии в портфолио'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='side_bar',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
